### ISSUE TITLE
CPU Clock Speed stuck at 0.55 Ghz

### ISSUE THREAD

**Issue by Avzen1010** [FrameworkComputer/SoftwareFirmwareIssueTracker#118]
### System Model or SKU

- [ ] Framework Laptop 16 (AMD Ryzen™ 7040 Series)

### BIOS VERSION
3.07

Windows:
Open a command terminal as administrator:
```wmic bios get SMBIOSBIOSVERSION```
wmic : The term 'wmic' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ wmic bios get SMBIOSBIOSVERSION
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (wmic:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

### DIY Edition information
If you are experiencing an issue on a DIY system, Please also fill out the memory and storage devices you are using. 

Memory: Manufacture and SKU
Crucial 16GB DDR5 SDRAM Memory Module (CT16G56C46S5)
CT16G56C46S5
Storage: Manufacture and SKU
Kingston
SNV3SM3/2T0

### Port/Peripheral information
Expansion cards do not effect this issue. I am using the 7700S Graphics module

### Standalone Operation
Are you running your mainboard as a standalone device. Is standalone mode enabled in the BIOS?
- [ X ] Yes

## Describe the bug
My framework laptop 16 CPU clock seems to be stuck at 0.55 GHz in some scenarios after I use the computer when it entered sleep mode. The current situations I’ve found to trigger it are playing helldivers 2, opening the search menu in windows, and being on a zoom call. If I restart the computer everything is fine, but it is quite annoying because I like the convivence of shutting the lid to put the laptop to sleep to save battery, but then I open it and it is incredibly slow. Also, this doesn’t change if I plug the laptop in or not or if power saving mode is on or off.

## Steps To Reproduce
Put the laptop to sleep or have it run for about a day

## Expected behavior
Running at at least 4.0 gHz

## Operating System (please complete the following information):
 - Windows
 - 11
 
## Additional context
https://community.frame.work/t/framework-16-stuck-at-0-55-ghz-after-windows-sleep-mode/73136

**Comment by quinchou77** [comment]
How many watts adapter do you connected on the system? We are now verifying the new BIOS with the PROHOT solution.
Will be released soon.

**Comment by Avzen1010** [comment]
A 180 watt adapter.

**Comment by npry** [comment]
I have a Framework 16 with the 7840, and I'm seeing the same symptom on both Windows 11 and Linux (kernel 6.16.0), and I've narrowed it down to when [my power adapter](https://www.amazon.com/dp/B0DFLTJ588) (140W) is connected through a [USB-C Hub](https://www.amazon.com/dp/B0CXSL7BDP) (the links are the specific devices I'm using). As soon as I disconnect the power adapter from the hub, my CPU clock goes back to normal. I can use the same adapter on any port on the Framework as long as I plug it in directly, charges fine, no problem with CPU clock. It's only if it's plugged in through the adapter. I triple-checked that I'm plugging the adapter into the power port on the USB hub. Also tried moving the USB hub to different ports on the Framework and disconnecting all the devices from it &mdash; it's the same issue in all configurations. Works fine if the power adapter isn't connected through the hub, CPU clock drops to 0.55GHz when it is.

This started happening spontaneously today &mdash; I had previously been using the same hub and power adapter in the same configuration for several days without this clock issue. The only thing I can think of that I did differently today was wake the laptop with its lid closed through the USB-C hub using a USB kb/mouse &mdash; I hadn't done that previously. I was on 3.05 firmware when the issue occurred, and I tried upgrading to 3.07 firmware before I realized that the adapter through the hub was the problem. 3.07 didn't fix it.

**Comment by TK0130** [comment]
Started happening to me recently has well. I have tried with multiple anker (35, 65, and 95W chargers) and several PD-EPR chargers from various brands (140, 180, and 240W). Even happens unplugged.

Fresh windows install, Bios V4.0.2 and driver bunder have the same issues. I suspected it had to do with sleep states for a long time but I have found I can trigger it by opening Overwatch and closing it several times. Oddly the CPU clock speed only clamps to 0.55GHz in specific software. (Rendering/CAD in fusion-360/blender is fine, overwatch breaks it sometimes. Solidworks breaks it but Autocad doesn't.)

**Comment by quinchou77** [comment]
We have released BIOS v4.03 Beta, which includes several critical power-related corrections. Please test this latest version and provide feedback. We are aiming for a stable release by next week.
https://community.frame.work/t/framework-laptop-16-ryzen-7040-bios-4-03-release-beta/79274/1

**Comment by Thogor** [comment]
I have the same model and it's already on 0.0.4.3 (has been for a while now). The issue is still not solved.

It always starts with Gnome indicating that the laptop is not plugged in (missing lightning indicator top right) even though it is. I have disabled the setting that stops your laptop from charging when it reaches a certain threshold so that's not causing it.

When the above starts, after a while, the laptop will inevitably get into a faulty throttling state where it limits the CPU to ~1,1 Ghz. It's usually triggered by being under heavy load for a while (compiling code or running some heavy duty integration tests).

So the first symptom is always the faulty "plugged in" state (Gnome top right battery icon missing the lightning bolt).
Next it will limit the CPU when the laptop experiences heavy load for a while.

**Comment by quinchou77** [comment]
We are still finding it difficult to reproduce the 545MHz frequency lock in our lab. To help us isolate the root cause, could anyone experiencing this issue perform a Battery Isolation Test?

**The Test:**
1. Disconnect the internal battery and run the system on AC power only (using the 180W adapter).
2. Attempt the same steps(such like Sleep/Wake) that previously triggered the 545MHz lock.

**Comment by Avzen1010** [comment]
I actually haven’t experienced this issue since 4.03 which seems to have completely solved the issue for me. I don’t know if why everyone else is describing is a different issue masquerading as the same thing.

**Comment by Toykio** [comment]
I'm still having roughly the same issue. Plugging the charger in via the USB C hub is causing it nearly always. If it doesn't i can get lucky to start one program (game or CAD) and it usually throttles again if i Alt+Tab or quit the program and start a different one.

The workaround with removing the USB C hub and charging directly at the USB C connector seems to be working, but obviously isn't a viable long term solution but it does feel like that might be the source of the problem. 

Opened up a support ticket and am available to run test if needed.
