### ISSUE TITLE
FW16 7040 Firmware update 0.0.3.7 -> 0.0.4.4: Fans not detected despite fans working

### ISSUE THREAD

**Issue by raldone01** [FrameworkComputer/SoftwareFirmwareIssueTracker#131]
### System Model or SKU

Framework Laptop 16 (AMD Ryzen™ 7040 Series)

### BIOS VERSION
`0.0.4.4` or `4.0.4` or `04.04`

### DIY Edition information
If you are experiencing an issue on a DIY system, Please also fill out the memory and storage devices you are using. 

Memory: Stock
Storage: SSD 980 PRO 2TB

### Standalone Operation
Are you running your mainboard as a standalone device. Is standalone mode enabled in the BIOS?
- [ ] Yes
- [x] No

## Describe the bug

Since updating the uefi to 0.0.4.2 the laptop complains about fans not being detected and directs me to the GPU install page? I have the storage expansion in the expansion bay.

Note: It would be nice to add a table of all prior uefi versions and their respective cab file download links on the uefi update page for ease of downgrades after failures/regressions: https://fwupd.org/lvfs/devices/work.frame.Laptop16.Ryzen7040.BIOS.firmware

## Steps To Reproduce
1. Install the firmware update and reboot.

## Expected behavior
No fan error should be displayed.

## Screenshots

![Image](https://github.com/user-attachments/assets/eec21bea-f684-4832-8b59-338c849547f7)
![Image](https://github.com/user-attachments/assets/93e9642b-2cff-429c-a221-b574f695fb42)

## Operating System (please complete the following information):
 - OS/Distribution: arch
 - Version: Rolling
- Linux Kernel Version: `Linux Elizabeth 6.17.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 14 Nov 2025 06:54:07 +0000 x86_64 GNU/Linux`

## Additional context

```
Framework Laptop 16 (AMD Ryzen 7040 Series)
│
├─CT4000P3PSSD8:
│     Device ID:          71b677ca0f1bc2c5b804fa1d59e52064ce589293
│     Summary:            NVM Express solid state drive
│     Current version:    P9CR40A
│     Vendor:             Micron/Crucial Technology (PCI:0xC0A9)
│     Serial Number:      2321E6DBA36F
│     GUIDs:              024834f2-5768-5565-b929-e3f57c0fcd69 ← NVME\VEN_C0A9&DEV_540A
│                         6d4f3936-021a-57df-bbd9-493e8f74da7e ← NVME\VEN_C0A9&DEV_540A&SUBSYS_C0A95021
│                         614653d4-7456-5704-a4bc-bc9994adb8cd ← CT4000P3PSSD8
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Can tag for emulation
│
├─Fingerprint Sensor:
│     Device ID:          a6ac74eb9d266e92632936d19976d755b043b55c
│     Summary:            Match-On-Chip fingerprint sensor
│     Current version:    01000334
│     Vendor:             Goodix (USB:0x27C6)
│     Install Duration:   10 seconds
│     Serial Number:      UID05E81A15_XXXX_MOC_B0
│     GUID:               1e8c8470-a49c-571a-82fd-19c9fa32b8c3 ← USB\VID_27C6&PID_609C
│     Device Flags:       • Updatable
│                         • Supported on remote server
│                         • Device stages updates
│                         • Device can recover flash failures
│                         • Signed Payload
│                         • Can tag for emulation
│
├─HDMI Expansion Card:
│     Device ID:          d787669ee4a103fe0b361fe31c10ea037c72f27c
│     Current version:    3.0.16.106
│     Bootloader Version: 3.0.2.900
│     Vendor:             Framework (USB:0x32AC)
│     Serial Number:      11AD1D009E5C3F12202F0B00
│     GUIDs:              ff59aed5-f8a7-5742-901a-1876d48ea0b5 ← USB\VID_32AC&PID_0002
│                         7cffc965-2ead-5c70-bd62-ce81a42d37fc ← USB\VID_32AC&PID_0002&MODE_FW2
│     Device Flags:       • Updatable
│                         • Device stages updates
│                         • Unsigned Payload
│                         • Can tag for emulation
│
├─Hub:
│     Device ID:          b8a2645298053fb62ea03e27feea6c483d3fd27e
│     Current version:    34.4
│     Vendor:             Genesys Logic, Inc. (USB:0x05E3)
│     Install Duration:   9 seconds
│     GUIDs:              50f5a84a-b3a3-50e3-aaa0-bec7853ce9a5 ← USB\VID_05E3&PID_0610&IC_359020&BONDING_78
│                         c4d81c30-cf18-556d-88fa-f21114558764 ← USB\VID_05E3&PID_0610&IC_359020&BONDING_78&RUNMODE_C
│                         f7937235-1a31-52a8-896f-7da42281ff27 ← USB\VID_05E3&PID_0610&VENDOR_GENESYSLOGIC&IC_359020&BONDING_78&PORTNUM_34&VENDORSUP_F90BEF00-53BB-5B38-8D56-7E8844A55516
│                         a786a1df-951f-5f77-81b4-aa07f3d10348 ← USB\VID_05E3&PID_0610&PROJECT_44859ED7-2D4D-5FE8-AA4A-D9A98B8B09F9
│     Device Flags:       • Updatable
│                         • Cryptographic hash verification is available
│                         • Unsigned Payload
│                         • Can tag for emulation
│
├─Laptop 16 Keyboard Module - ANSI:
│     Device ID:          c76174094144e363df0c2b6d9e511ebfce89ed7d
│     Current version:    0.31
│     Vendor:             Framework (HIDRAW:0x32AC)
│     GUID:               bf9a4319-494f-5c88-9637-72f97222cac9 ← HIDRAW\VEN_32AC&DEV_0012
│     Device Flags:       • Internal device
│                         • Updatable
│                         • Unsigned Payload
│                         • Can tag for emulation
│
├─Laptop 16 Numpad Module:
│     Device ID:          e6e8ffd21cef22ff24a6c71ce20499d56d34a73f
│     Current version:    0.31
│     Vendor:             Framework (HIDRAW:0x32AC)
│     GUID:               7812afb5-8506-5e90-8881-8f5f9a5b0e75 ← HIDRAW\VEN_32AC&DEV_0014
│     Device Flags:       • Internal device
│                         • Updatable
│                         • Unsigned Payload
│                         • Can tag for emulation
│
├─Ryzen 7 7840HS w/ Radeon 780M Graphics:
│ │   Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│ │   Current version:    0x0a70410a
│ │   Vendor:             AMD
│ │   GUIDs:              2a1df9de-fe02-59c8-8af1-32c8bb011f94 ← CPUID\PRO_0&FAM_19&MOD_74
│ │                       5a4bca32-6547-584f-bb36-920d9adede25 ← CPUID\PRO_0&FAM_19&MOD_74&STP_1
│ │   Device Flags:       • Internal device
│ │
│ ├─Radeon 780M Graphics:
│ │     Device ID:        ab66dd4442bdf3ad5d4101887804658d6045632a
│ │     Summary:          AMD AMD_PHOENIX_GENERIC
│ │     Current version:  1
│ │     Vendor:           AMD (PCI:0x1002)
│ │     GUID:             4a1501b7-b500-5255-9d9c-41d652a4d5bc ← AMD\113-PHXGEN
│ │     Device Flags:     • Internal device
│ │                       • Can tag for emulation
│ │
│ ├─Secure Processor:
│ │     Device ID:        c54ab0237d7a8db8c717b68e0be78e4374a2a079
│ │     Summary:          AGESA PhoenixPI-FP8-FP7 1.2.0.0c
│ │     Current version:  00.2d.00.86
│ │     Bootloader Version: 00.2d.00.86
│ │     Vendor:           AMD (PCI:0x1022)
│ │     GUID:             9eb6a793-7f97-5fb5-b49c-139d2ce3ee46 ← PCI\VEN_1022&DEV_15C7
│ │     Device Flags:     • Internal device
│ │                       • Can tag for emulation
│ │
│ ├─System Management Unit (SMU):
│ │     Device ID:        db0330716216c629bb2c07256e5d018f499eb6ce
│ │     Summary:          Microcontroller used within CPU/APU program 0
│ │     Current version:  76.96.0
│ │     Vendor:           AMD
│ │     GUID:             3ac3159e-6eef-5f6b-bc8d-67686b238747 ← /sys/devices/platform/AMDI0009:00
│ │     Device Flags:     • Internal device
│ │                       • Can tag for emulation
│ │
│ └─TPM:
│       Device ID:        1d8d50a4dbc65618f5c399c2ae827b632b3ccc11
│       Current version:  6.4.1.383
│       Vendor:           Microsoft (TPM:MSFT)
│       GUIDs:            2a65d4b6-60a0-5e8c-acfa-d86cc3cbe4c3 ← TPM\VEN_MSFT&DEV_0001
│                         31a7bb1b-f5e1-53ff-b0e5-8692a21caed6 ← TPM\VEN_MSFT&MOD_Pluton.TPM.A
│                         5bea8d58-c840-513e-a5ad-0184cbaa9821 ← TPM\VEN_MSFT&DEV_0001&VER_2.0
│                         e02519c6-9139-5de8-89d4-9dca2f5c3b66 ← TPM\VEN_MSFT&MOD_Pluton.TPM.A&VER_2.0
│       Device Flags:     • Internal device
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device can recover flash failures
│                         • Signed Payload
│                         • Can tag for emulation
│
├─SSD 980 PRO 2TB:
│     Device ID:          3743975ad7f64f8d6575a9ae49fb3a8856fe186f
│     Summary:            NVM Express solid state drive
│     Current version:    5B2QGXA7
│     Vendor:             Samsung (PCI:0x144D)
│     Serial Number:      S69ENX0TC09596T
│     GUIDs:              bec63ed7-a95f-54fe-b8cc-8e9fee64ba5a ← NVME\VEN_144D&DEV_A80A
│                         310f81b5-6fce-501e-acfb-487d10501e78 ← NVME\VEN_144D&DEV_A80A&SUBSYS_144DA801
│                         c8bffd05-1744-5cdd-ad4d-0fbc3b20e3c2 ← Samsung SSD 980 PRO 2TB
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│                         • Can tag for emulation
│
└─System Firmware:
  │   Device ID:          7010981714ee5c9258de42216cae163ef272c7ab
  │   Summary:            UEFI System Resource Table device (Updated via capsule-on-disk)
  │   Current version:    0.0.4.2
  │   Minimum Version:    0.0.3.5
  │   Vendor:             Framework (DMI:INSYDE Corp.)
  │   Update State:       Success
  │   GUID:               6ae76af1-c002-5d64-8e18-658d205acf34
  │   Device Flags:       • Internal device
  │                       • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Needs a reboot after installation
  │                       • Cryptographic hash verification is available
  │                       • Device is usable for the duration of the update
  │   Device Requests:    • Message
  │
  ├─Platform Key:
  │     Device ID:        6924110cde4fa051bfdc600a60620dc7aa9d3c6a
  │     Summary:          UEFI Platform Key
  │     Current version:  2024
  │     Vendor:           Unknown
  │     GUID:             5451f72c-f83c-5496-84ff-61e64ae398ab ← UEFI\CRT_2C31E1EB92664370A58B2217FF12E8D0D12CAE6F
  │     Device Flags:     • Internal device
  │
  ├─UEFI Key Exchange Key:
  │ │   Device ID:        2a4c23bfb79b5dabe474cb7b1b3e604645d6f9c6
  │ │   Device Flags:     • Internal device
  │ │
  │ ├─KEK CA:
  │ │     Device ID:      b7a1d3d90faa1f6275d9a98da4fb3be7118e61c7
  │ │     Current version: 2011
  │ │     Vendor:         Microsoft (UEFI:Microsoft)
  │ │     GUIDs:          814e950f-1449-566a-a190-42c9d3a3a2df ← UEFI\VENDOR_Microsoft&NAME_Microsoft-KEK-CA
  │ │                     dfa66406-6568-5bdf-bb8e-b53ddb4be4cf ← UEFI\CRT_9F402B1CC0243CBEDC58A525789816CCCA7687A9
  │ │     Device Flags:   • Internal device
  │ │                     • Updatable
  │ │                     • Needs a reboot after installation
  │ │                     • Device is usable for the duration of the update
  │ │                     • Signed Payload
  │ │                     • Can tag for emulation
  │ │
  │ └─Key Exchange Key:
  │       Device ID:      7227626d9209595851b3840e3d626601a375ce2d
  │       Current version: 2024
  │       Update Error:   No vendor ID set
  │       GUID:           ad4972b1-c98e-5ca7-9fd4-257d33e2ad99 ← UEFI\CRT_2E9F57E1A49A6593D07E7D5383489A6370EFA016
  │       Device Flags:   • Internal device
  │                       • Needs a reboot after installation
  │                       • Device is usable for the duration of the update
  │                       • Updatable
  │                       • Signed Payload
  │                       • Can tag for emulation
  │
  ├─UEFI Signature Database:
  │ │   Device ID:        0352a8acc949c7df21fec16e566ba9a74e797a97
  │ │   Device Flags:     • Internal device
  │ │
  │ ├─Database Key:
  │ │     Device ID:      0e3b4bfc8e1d26fa79855e17c4a13e4f4ddf316f
  │ │     Current version: 2024
  │ │     Update Error:   No vendor ID set
  │ │     GUID:           73701685-efe6-5d5f-a9a2-1b5b06b1f6d1 ← UEFI\CRT_9552667ABDC43FE2CD1E6A67F2C83693B5D7E2C4
  │ │     Device Flags:   • Internal device
  │ │                     • Needs a reboot after installation
  │ │                     • Updatable
  │ │                     • Signed Payload
  │ │                     • Can tag for emulation
  │ │
  │ ├─Option ROM UEFI CA:
  │ │     Device ID:      92120fc1a625f725901333cbfec152b8d6e42d43
  │ │     Current version: 2023
  │ │     Vendor:         Microsoft (UEFI:Microsoft)
  │ │     GUIDs:          ca4668d9-734f-5b2b-aae8-8120b196f659 ← UEFI\VENDOR_Microsoft&NAME_Microsoft-Option-ROM-UEFI-CA
  │ │                     965d1919-0e18-5b63-9ebd-e5d122cd11df ← UEFI\CRT_F45B559FC1C60F31B3071021298D5ED7D77280B0
  │ │     Device Flags:   • Internal device
  │ │                     • Updatable
  │ │                     • Needs a reboot after installation
  │ │                     • Signed Payload
  │ │                     • Can tag for emulation
  │ │
  │ ├─UEFI CA:
  │ │     Device ID:      5bc922b7bd1adb5b6f99592611404036bd9f42d0
  │ │     Current version: 2023
  │ │     Vendor:         Microsoft (UEFI:Microsoft)
  │ │     GUIDs:          26f42cba-9bf6-5365-802b-e250eb757e96 ← UEFI\VENDOR_Microsoft&NAME_Microsoft-UEFI-CA
  │ │                     308281c7-d0c5-52e0-8c1a-810540de03df ← UEFI\CRT_7CD7437C555F89E7C2B50E21937E420C4E583E80
  │ │     Device Flags:   • Internal device
  │ │                     • Updatable
  │ │                     • Supported on remote server
  │ │                     • Needs a reboot after installation
  │ │                     • Signed Payload
  │ │                     • Can tag for emulation
  │ │
  │ └─Windows Production PCA:
  │       Device ID:      ad7e00ec37f005ae10492bdb7f73aef0d2e20488
  │       Current version: 2011
  │       Vendor:         Microsoft (UEFI:Microsoft)
  │       GUIDs:          675d2184-6c9a-59f1-a6f1-3c229b5dbb79 ← UEFI\VENDOR_Microsoft&NAME_Microsoft-Windows-Production-PCA
  │                       0611d85d-99a4-5c50-8c17-fc5196226f85 ← UEFI\CRT_1A8B6903D64CC9AD09D12FCB355663A458A09EF0
  │       Device Flags:   • Internal device
  │                       • Updatable
  │                       • Needs a reboot after installation
  │                       • Signed Payload
  │                       • Can tag for emulation
  │
  └─UEFI dbx:
        Device ID:        362301da643102b9f38477387e2193e57abaa590
        Summary:          UEFI revocation database
        Current version:  20250902
        Minimum Version:  20250902
        Vendor:           Microsoft (UEFI:Microsoft)
        Install Duration: 1 second
        GUIDs:            3bf2bb02-b0b8-5013-afb6-c9ebde785306 ← UEFI\CRT_CA23D6026B02CEA851A46A39BE5C7F931BAE2D0175F7E59DE791B2238833F2D8&ARCH_X64
                          f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
        Device Flags:     • Internal device
                          • Updatable
                          • Supported on remote server
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
                          • Only version upgrades are allowed
                          • Signed Payload
                          • Can tag for emulation
```

Relevant forum post: https://community.frame.work/t/firmware-update-0-0-4-2-fans-not-detected-despite-fans-working/78077

**Comment by neroun-100y5d** [comment]
Maybe this update helps.
[ceeb03db020f.zip](https://github.com/user-attachments/files/23653049/ceeb03db020f.zip)

**Comment by raldone01** [comment]
@neroun-100y5d is a spam bot and that zip file contains probably malicious code called `ranlib`.

**Comment by raldone01** [comment]
Downgrading to `3.07` fixes the issue and the fan warning goes away.

**Comment by quinchou77** [comment]
We just released the the BIOS 4.03 beta, which enhance the FAN detect mechanism.
https://community.frame.work/t/framework-laptop-16-ryzen-7040-bios-4-03-release-beta/79274/1

**Comment by raldone01** [comment]
Thank you!

I will test it in the new year.

**Comment by rglovinsky** [comment]
I updated to the 4.03 BIOS, but it appears I still get the "Right fan not detected" error on reboot. I didn't have any issues until the 4.02, which would cause either Right or both fans to not be detected. So far 4.03 has only shown the Right fan not detected.

**Comment by raldone01** [comment]
Update: 4.03 BIOS still doesn't fix fan detection. It alerts me every boot that the fans are not installed.
Both fans are working properly in the OS.

**Comment by raldone01** [comment]
I just booted the laptop a few times with the input plate (the metal thing with many screws) removed. Then the fans spin during preboot and the uefi detects the fans correctly.
When I install the plate the fans are no longer detected though.

**Comment by lefthandedbears** [comment]
Issue has started here with the 4.03 BIOS - I did NOT have the fan detection issue and now that I've updated I keep getting "left fan not detected" while I can hear it running.

**Comment by lefthandedbears** [comment]
> I just booted the laptop a few times with the input plate (the metal thing with many screws) removed. Then the fans spin during preboot and the uefi detects the fans correctly. When I install the plate the fans are no longer detected though.

Just attempted this as well.  Could see both fans working with the mid-plate removed.  Booted without the error. Re-installed mid-plate, keyboard, etc. and error came back - "left fan not detected"

**Comment by sefalkner** [comment]
Just jumping in to say that I experience the same with my AI 300 series FW16. See #172 .

Other people get it too:
https://community.frame.work/t/fans-not-detected-in-ai-300-series/79696/3

I even got a new mainboard and then even a replacement laptop and the issue is still there. So slim chance it's the hardware, also having your experiences in mind.

I'd be happy to get some updates in case you made some progress.

**Comment by raldone01** [comment]
Still happens with 0.0.4.4. I am going to file an rma.
The message changed to left fan not detected though.

**Comment by raldone01** [comment]
Was a hardware issue. RMA replaced the mainboard. Now it works.
